name: Build streamer

env:
  CARGO_TERM_COLOR: always

on: workflow_dispatch

jobs:
  build_windows_streamer:
    runs-on: windows-2022
    env:
      # For bindgen to find libclang.dll, we need to give it the path to the Visual Studio package.
      # This is specific to the GitHub windows-2019 runner.
      LIBCLANG_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\Llvm\x64\bin'
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - uses: dtolnay/rust-toolchain@stable

      - uses: crazy-max/ghaction-chocolatey@v4
        with:
          args: install zip unzip pkgconfiglite

      - name: Build and package ALVR
        id: build
        env:
          RUST_BACKTRACE: 1
        run: |
          cargo xtask package-streamer --gpl --ci
          cargo xtask package-launcher --ci

      - name: Upload streamer
        uses: actions/upload-artifact@v7
        with:
          name: alvr_streamer_windows.zip
          path: ./build/alvr_streamer_windows.zip
      - name: Upload launcher
        uses: actions/upload-artifact@v7
        with:
          name: alvr_launcher_windows.zip
          path: ./build/alvr_launcher_windows.zip

  build_linux_streamer:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - uses: dtolnay/rust-toolchain@stable

      - name: Build and install dependencies
        env:
          RUST_BACKTRACE: 1
        run: |
          sudo apt-get update
          sudo apt-get install libfuse2 build-essential pkg-config cmake nasm libva-dev libdrm-dev libvulkan-dev libx264-dev libx265-dev libasound2-dev libjack-jackd2-dev libxrandr-dev libunwind-dev libffmpeg-nvenc-dev libgtk-3-dev libpipewire-0.3-dev libspa-0.2-dev

      - name: Build and package ALVR (.tar.gz)
        id: build
        env:
          RUST_BACKTRACE: 1
        run: |
          cargo xtask package-streamer --gpl --ci
          cargo xtask package-launcher --ci

      - name: Upload streamer (tar.gz)
        uses: actions/upload-artifact@v7
        with:
          name: alvr_streamer_linux.tar.gz
          path: ./build/alvr_streamer_linux.tar.gz
      - name: Upload launcher
        uses: actions/upload-artifact@v7
        with:
          name: alvr_launcher_linux.tar.gz
          path: ./build/alvr_launcher_linux.tar.gz
